version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  knot-crawler:
    build:
      context: .
      dockerfile: images/crawler/Dockerfile
    environment:
      PG_HOST: postgres
    depends_on:
      - postgres

  knot-view:
    build:
      context: .
      dockerfile: images/view/Dockerfile
    environment:
      PG_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '8080:${PORT:-8080}'

        
volumes:
  db: