apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: knot-cralwer
  template:
    metadata:
      labels:
        app: knot-cralwer
    spec:
      containers:
        - name: node-knot-crawler
          image: headgardener/knot-crawler:1.0.0
          env:
          - name: PG_HOST
            value: "postgres"
